# Generated by Django 6.0.2 on 2026-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_remove_booking_time_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Restaurant Owner'), ('customer', 'Customer')], max_length=20),
        ),
    ]
