# Generated by Django 6.0.2 on 2026-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Restaurant Owner'), ('customer', 'Customer')], max_length=20),
        ),
    ]
