# Generated by Django 6.0.2 on 2026-03-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(upload_to='restaurant_images/'),
        ),
    ]
