# Generated by Django 6.0.2 on 2026-03-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='slot_duration',
            field=models.IntegerField(default=15),
        ),
    ]
