# Generated by Django 6.0.2 on 2026-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(default='Lunch', max_length=100),
            preserve_default=False,
        ),
    ]
