# Generated by Django 6.0.2 on 2026-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_menu_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=100),
        ),
    ]
